### ISSUE TITLE
doesn't work in vs 2019 community

### ISSUE THREAD

**Issue by ma3yta** [hlizard/HideTitleBar#1]

**Comment by peterson1** [comment]
Me too. I can't install it on VS 2019 Community.
It throws this error:
This extension cannot be installed because the following references are missing: Microsoft.VisualStudio.Component.CoreEditor

**Comment by AlexVPerl** [comment]
Getting the same error upon opening VS after extension install. Would be great if dev could look into it. Would love to use this extension. Thanks!

**Comment by alikalfaoglu** [comment]
Same with all editions for VS2019. Using Enterprise and Pro in my team..

**Comment by ma3yta** [comment]
https://marketplace.visualstudio.com/items?itemName=Poma.MinimalisticView
works fine
